# Generated by Django 4.1.7 on 2023-03-12 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Almacenes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almacen', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=50)),
                ('modelo_producto', models.CharField(max_length=50)),
                ('serial_producto', models.CharField(max_length=50, unique=True)),
                ('cantidad_producto', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.EmailField(max_length=254)),
                ('departamento', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Solicitudes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=10)),
                ('serial', models.CharField(max_length=20)),
                ('cantidad_solicitada', models.PositiveIntegerField(default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.productos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('cantidad_movimiento', models.CharField(max_length=10)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.almacenes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.productos')),
            ],
        ),
        migrations.AddField(
            model_name='almacenes',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.productos'),
        ),
    ]
