# Generated by Django 4.1.7 on 2023-03-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudes',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='solicitudes',
            name='serial',
        ),
        migrations.AddField(
            model_name='solicitudes',
            name='estado',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='solicitudes',
            name='cantidad_solicitada',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
